name: Alira Core Actions
description: >
  Composite Action that checks out code, generates a diff patch,
  runs an AI analysis agent, and opens a GitHub Issue with the
  Markdown-formatted results.

inputs:
  github_token:
    description: 'GitHub token for authentication'
    required: true

  cleanup:
    description: 'Whether to delete pr_repo after run (true/false)'
    required: false
    default: 'false'

  system_prompt_path:
    description: '시스템 프롬프트 파일 경로 (유저 레포 기준, 없으면 기본값 사용)'
    required: false
    default: ''

  user_prompt_path:
    description: '사용자 프롬프트 파일 경로 (유저 레포 기준, 없으면 기본값 사용)'
    required: false
    default: ''

  project_name:
    description: '프로젝트 이름'
    required: false
    default: 'pr_project'

runs:
  using: composite
  steps:
    # 0. (항상) 이전에 있던 pr_repo 지우기
    - name: Cleanup pr_repo
      run: rm -rf ${{ github.workspace }}/pr_repo
      shell: bash

    # 1. Checkout
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ inputs.github_token }}
        path: pr_repo
        fetch-depth: 0

    # 2. PR 이벤트면 base 브랜치 대비 diff 생성
    - name: Generate patch file for PR
      if: ${{ github.event_name == 'pull_request' }}
      run: |
        cd ${{ github.workspace }}/pr_repo
        git fetch origin ${{ github.event.pull_request.base.ref }}
        git diff origin/${{ github.event.pull_request.base.ref }} HEAD > /tmp/pr.patch
      shell: bash

    # 3. Push 이벤트면 before→after diff 생성
    - name: Generate patch file for push
      if: ${{ github.event_name == 'push' }}
      run: |
        cd ${{ github.workspace }}/pr_repo
        git diff ${{ github.event.before }} ${{ github.event.after }} > /tmp/pr.patch
      shell: bash

    # 4. AI 에이전트 실행 및 결과 Markdown으로 저장
    - name: Run AI Analysis and save output
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
      run: |
        set -euo pipefail

        # 1) args 배열 생성 (따옴표는 요소를 감쌀 때만!)
        args=(
          --patch-path /tmp/pr.patch
          --project-root "${{ github.workspace }}/pr_repo"
          --output-path /tmp/analysis.md
          --project-name "${{ inputs.project_name }}"
        )

        # 2) optional prompts
        if [ -n "${{ inputs.system_prompt_path }}" ]; then
          args+=(--system-prompt-path "${{ github.workspace }}/pr_repo/${{ inputs.system_prompt_path }}")
        fi
        if [ -n "${{ inputs.user_prompt_path }}" ]; then
          args+=(--user-prompt-path "${{ github.workspace }}/pr_repo/${{ inputs.user_prompt_path }}")
        fi

        # 3) 실행 (배열 언패킹)
        uv run --directory /home/sure/alira-ai \
          --package core core/examples/action.py "${args[@]}"


    # 5. GitHub Issue 생성
    - name: Create GitHub Issue
      if: ${{ always() }}
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
      run: |
        set -euo pipefail

        SHORT_SHA=${GITHUB_SHA:0:7}

        # pull_request 인지 push 인지 판단
        if [ "$GITHUB_EVENT_NAME" = "pull_request" ]; then
          TITLE="AI Analysis for PR #${PR_NUMBER}"
        else
          TITLE="AI Analysis for commit ${SHORT_SHA}"
        fi

        # Issue 생성
        gh issue create \
          --title "$TITLE" \
          --body-file /tmp/analysis.md \
          --repo "$GITHUB_REPOSITORY"

    # 6. (선택) pr_repo 삭제
    - name: Cleanup pr_repo (optional)
      if: ${{ inputs.cleanup == 'true' }}
      run: rm -rf ${{ github.workspace }}/pr_repo
      shell: bash
